#!/bin/bash

set -xeuo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin

# must be different between branches
# it allows easy branch switching
# without need for rebuild
drupal_root=drupal9

cd /app

set +e
rm -rf "$drupal_root"
chmod -R 777 "$drupal_root"
rm -rf "$drupal_root"
set -e

# NB! When Composer breaks:
# https://www.drupal.org/project/drupal/issues/3255749
composer create-project drupal/recommended-project "$drupal_root"

web="/app/$drupal_root/web"
chmod 755 "$web/sites/default"
rm -f "$web/sites/default/settings.php"
ln -s /app/settings.php "$web/sites/default/settings.php"
ln -s /app/_ping.custom.php "$web/"
ln -s /app/_ping.php "$web/"

cd "/app/$drupal_root"
composer require --dev drush/drush
