#!/bin/bash

set -xeuo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin

# must be different between branches
# it allows easy branch switching
# without need for rebuild
app="/app"
proj="$app/drupal"
webroot="$proj/web"
sites="$webroot/sites"
default="$sites/default"
pingroot="$app/drupal-ping"

set +e
rm -rf "$proj"
chmod -R 777 "$proj"
rm -rf "$proj"
set -e

# NB! When Composer breaks:
# https://www.drupal.org/project/drupal/issues/3255749
cd "$app"
composer create-project drupal/recommended-project "$proj"

chmod 755 "$default"
rm -f "$default/settings.php"
ln -s "$pingroot/settings.php" "$default/"
ln -s "$pingroot/_ping.custom.php" "$webroot/"
ln -s "$pingroot/_ping.php" "$webroot/"
chmod 644 "$pingroot/settings.php"

cd "$proj"
composer require --dev drush/drush
composer require 'wunderio/code-quality:^2' --dev
composer require 'phpunit/phpunit:^9' --dev