#!/bin/bash

set -euo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/app/vendor/bin

cd /app

set -x

php -l _ping.php
php -l settings.php
phpcs -sp --report=full --runtime-set testVersion 7.4 --standard=Drupal,DrupalPractice,Security,PHPCompatibility,VariableAnalysis,WunderDrupal,WunderSecurity _ping.php settings.php
phpstan analyze --level=5 --autoload-file scan-autoload.php -- _ping.php settings.php
psalm
