#!/bin/bash

set -euo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/app/drupal/vendor/bin

# Due to autoloader issues need to run the scan on linked _ping.php in drupal webroot.
cd /app/drupal/web

set -x

php -l _ping.php
phpcs -sp --report=full --runtime-set testVersion 7.4 --standard=Drupal,DrupalPractice,Security,PHPCompatibility,VariableAnalysis,WunderDrupal,WunderSecurity _ping.php
phpstan analyze --level=5 -- _ping.php
psalm --config=/app/psalm.xml
