#!/bin/bash

set -euo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/app/drupal/vendor/bin

cd /app/drupal

set -x

php -d memory_limit=-1 /app/drupal/vendor/bin/phpunit /app/tests
