#!/bin/bash

set -xeuo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin

export PATH="$PATH:/app/drupal/vendor/bin"

# cannot do this during the build
# because db is not available at the build time.
cd "/app/drupal"

set +e
drush status | grep -q -e 'Drupal bootstrap *: *Successful'
status="$?"
set -e
if [[ "$status" -ne 0 ]]; then
  ./vendor/bin/drush site-install standard -y
fi
